"""add pendaftar status

Revision ID: 0310c7ec9f60
Revises: a36bdd831a2f
Create Date: 2026-09-08 08:52:12.527664

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0310c7ec9f60'
down_revision = 'a36bdd831a2f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pendaftar', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pendaftar', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
