"""add pengurus table

Revision ID: fae7e5aec172
Revises: 0310c7ec9f60
Create Date: 2026-09-08 21:52:36.413507

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fae7e5aec172'
down_revision = '0310c7ec9f60'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pengurus',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nama', sa.String(length=120), nullable=False),
    sa.Column('jabatan', sa.String(length=120), nullable=False),
    sa.Column('foto', sa.String(length=255), nullable=True),
    sa.Column('deskripsi', sa.Text(), nullable=True),
    sa.Column('urutan', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pengurus')
    # ### end Alembic commands ###
